name: CI
on:
  push:
    branches:
      - master
      - ci-github-actions
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
        elixir:
          - '1.7'
        otp:
          - '21.0'
        include:
          - os: 'ubuntu-18.04'
            elixir: '1.4.5'
            otp: '20.3'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: mix local.hex --force
      - run: mix deps.get --only test
      - run: mix test
      - run: mix credo
      - run: MIX_ENV=docs mix deps.get
      - run: MIX_ENV=docs mix inch.report
